name: Update Profile README

on:
  schedule:
    - cron: '*/30 * * * *'   # runs every 30 minutes
  push:
    branches:
      - main
  workflow_dispatch:          # lets you trigger it manually too

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Recent Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
